
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "60"
use-conda: "False"
use-singularity: "True"
jobs: "24"
printshellcmds: "True"
default-resources:
  - runtime=100
  - mem_mb=5000
set-threads:
  - bcl2fastq=24
set-resources:
  - bcl2fastq:mem_mb=32000
