name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Dry_Run_and_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:stable
    - name: Dry Run with test data
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:stable \
        /opt2/bin/demux run -p /opt2/.tests/illumnia_demux -o /opt2/.tests/illumnia_demux/dry_run_out
    - name: View the pipeline config file
      run: |
        echo "Generated config file for pipeline...." && cat $PWD/output/config.json
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:stable snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
