name: Dry run dmux & lint Snakefile

on:
  push:


jobs:
  dry_run_and_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:stable
    - name: Dry Run with test data
      run: |
        docker run -h cn0000 -v $PWD:/opt2 -w /opt2 snakemake/snakemake:stable /bin/bash -c \
        "pip install -r requirements.txt;./dmux run -s /opt2/.tests/illumnia_demux -o /opt2/.tests/illumnia_demux/dry_run_out --local --dry-run /opt2/.tests/illumnia_demux"
    - name: View the pipeline config file
      run: |
        echo "Generated config file for pipeline...." && cat $PWD/.tests/illumnia_demux/dry_run_out/EXP_PROJ_demux/.config/config_job_0.json
    - name: Lint Snakefile
      continue-on-error: true
      run: |
        docker run -e SNK_CONFIG='/opt2/.tests/illumnia_demux/dry_run_out/.config/config_job_0.json' -v $PWD:/opt2 snakemake/snakemake:stable snakemake --lint -s /opt2/workflow/illumina/Snakefile -d /opt2/workflow/illumina || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
